name: node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: define nodejs
        run: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
      - name: Install Dependencies and Lint Backend and Frontend
        run: |
          npm install
          cd frontend
          npm install
          cd ../
      - name: linting
        run: |
          npm run lint-fix
          cd frontend
          npm run lint-fix
          cd ../
      - name: build Frontend
        run: |
          cd frontend
          npm run build
          cd ../



